
package com.telus.credit.crda.webservice.service;

import java.util.List;

import javax.annotation.Resource;
import javax.jws.HandlerChain;
import javax.jws.WebService;
import javax.xml.ws.BindingType;
import javax.xml.ws.WebServiceContext;

import com.telus.framework.ws.jaxws.SpringBeanLookupHelper;

import com.telus.credit.domain.common.CreditBureauDocument;
import com.telus.credit.domain.crda.CreditAssessmentRequest;
import com.telus.credit.domain.crda.CreditAssessmentTransaction;
import com.telus.credit.domain.crda.GetCreditAssessmentResponse.CreditAssessmentDetails;
import com.telus.credit.domain.crda.PerformCreditAssessmentResponse.CreditAssessmentTransactionResult;
import com.telus.credit.domain.crda.SearchCreditAssessmentsRequestCriteria;
import com.telus.credit.domain.ent.AuditInfo;
import com.telus.wsdl.cmo.ordermgmt.enterprisecreditassessmentservice_2.EnterpriseCreditAssessmentServicePortType;
import com.telus.wsdl.cmo.ordermgmt.enterprisecreditassessmentservice_2.PolicyException;
import com.telus.wsdl.cmo.ordermgmt.enterprisecreditassessmentservice_2.ServiceException;
/*import com.telus.credit.crda.exception.CreditAssessmentExceptionFactory;
import com.telus.credit.crda.exception.EnterpriseCreditAssessmentServiceException;*/
/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 *
 */
@WebService(
	portName = "EnterpriseCreditAssessmentServicePort", 
	serviceName = "EnterpriseCreditAssessmentService_v2_1", 
	targetNamespace = "http://telus.com/wsdl/CMO/OrderMgmt/EnterpriseCreditAssessmentService_2", 
	wsdlLocation = "/wsdls/EnterpriseCreditAssessmentService_v2_1.wsdl", 
	endpointInterface = "com.telus.wsdl.cmo.ordermgmt.enterprisecreditassessmentservice_2.EnterpriseCreditAssessmentServicePortType")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
@HandlerChain(file="handler-chain.xml")
public class EnterpriseCreditAssessmentServicePortImpl
    implements EnterpriseCreditAssessmentServicePortType
{
    @Resource
    private WebServiceContext m_webserviceCtx;
	private EnterpriseCreditAssessmentServicePortType m_entAsmtServiceImpl;

    public EnterpriseCreditAssessmentServicePortImpl() {
    }

    /**
     * 
     * @param creditAssessmentID
     * @param auditInfo
     * @return
     *     returns com.telus.credit.crda.domain.GetCreditAssessmentResponse.CreditAssessmentDetails
     * @throws PolicyException
     * @throws ServiceException
     */
    
    public CreditAssessmentDetails getCreditAssessment(long creditAssessmentID, AuditInfo auditInfo)
        throws PolicyException, ServiceException
    {
        return getEntCrdAsmtService().getCreditAssessment( creditAssessmentID,  auditInfo);
    }

    /**
     * 
     * @param creditBureauDocumentID
     * @param auditInfo
     * @return
     *     returns java.util.List<com.telus.tmi.xmlschema.xsd.customer.basetypes.creditcommon_v1.CreditBureauDocument>
     * @throws PolicyException
     * @throws ServiceException
     */
    public CreditBureauDocument getCreditBureauDocument(String creditBureauDocumentID, AuditInfo auditInfo)
        throws PolicyException, ServiceException
    {
		return getEntCrdAsmtService().getCreditBureauDocument(creditBureauDocumentID,  auditInfo);
    }

    /**
     * 
     * @param creditAssessmentRequest
     * @param auditInfo
     * @return
     *     returns com.telus.credit.crda.domain.CreditAssessmentTransaction
     * @throws ServiceException
     * @throws PolicyException
     */
    public CreditAssessmentTransactionResult performCreditAssessment(CreditAssessmentRequest creditAssessmentRequest, AuditInfo auditInfo)
        throws PolicyException, ServiceException
    {

    	
		return getEntCrdAsmtService().performCreditAssessment(creditAssessmentRequest,  auditInfo);
    }

    /**
     * 
     * @param searchCreditAssessmentsRequestCriteria
     * @param auditInfo
     * @return
     *     returns java.util.List<com.telus.credit.crda.domain.CreditAssessmentTransaction>
     * @throws PolicyException
     * @throws ServiceException
     */

	@Override
	public List<CreditAssessmentTransaction> searchCreditAssessmentList(
			SearchCreditAssessmentsRequestCriteria searchCreditAssessmentsRequestCriteria,
			AuditInfo auditInfo) throws PolicyException, ServiceException {
		return getEntCrdAsmtService().searchCreditAssessmentList(searchCreditAssessmentsRequestCriteria,  auditInfo);
		 
	}

    /**
     * 
     * @param creditAssessmentID
     * @param voidReasonCode
     * @param auditInfo
     * @throws PolicyException
     * @throws ServiceException
     */
	@Override
	public void voidCreditAssessment(long creditAssessmentID,
			String voidReasonCode, AuditInfo auditInfo) throws PolicyException,
			ServiceException {
        getEntCrdAsmtService().voidCreditAssessment(creditAssessmentID,  voidReasonCode, auditInfo);
        return;
		
	}    
    /**
     * 
     * @return
     *     returns java.lang.String
     * @throws PolicyException
     * @throws ServiceException
     */
    public String ping()
        throws PolicyException, ServiceException
    {
        
        return getEntCrdAsmtService().ping();
    }

	private EnterpriseCreditAssessmentServicePortType getEntCrdAsmtService() throws ServiceException {
		if (m_entAsmtServiceImpl ==null) {
			try {
				m_entAsmtServiceImpl = (EnterpriseCreditAssessmentServicePortType) SpringBeanLookupHelper.getBean(m_webserviceCtx,"enterpriseCreditAssessmentService");
			} catch (Exception e) {				
			        com.telus.tmi.xmlschema.xsd.common.exceptions.exceptions_v1_0.ServiceException faultInfo = new com.telus.tmi.xmlschema.xsd.common.exceptions.exceptions_v1_0.ServiceException();
			        faultInfo.setErrorCode("CRDA-SYS-003");
			        faultInfo.setErrorMessage(e.getMessage());
			        throw new ServiceException(e.getMessage(), faultInfo, e);				
				
/*				CreditAssessmentExceptionFactory.createServiceException(
						"getEntCrdAsmtService", 
						"" +
						"ERROR_LOADING_SPRING", 
						e);*/
			}
		}
		
		return m_entAsmtServiceImpl;
	}



	
}
