#!/usr/bin/ksh

echo "Step 8a: Joining the files from steps 1 and 2."

syncsort << EOF
   /JOIN unpaired rightside
   /INFILE "$1" 65535
   /JOINKEYS SORTED recordlayout1.SERVICE_INSTANCE_ID
   /INFILE "$2" 65535
   /JOINKEYS SORTED recordlayout2.SERVICE_INSTANCE_ID

   /OUTFILE "$3" 65535 OVERWRITE
   /REFORMAT LEFTSIDE:recordlayout1.BILLING_ACCOUNT_ID, RIGHTSIDE:recordlayout2.WTN, LEFTSIDE:recordlayout1.SERVICE_INSTANCE_ID, RIGHTSIDE:recordlayout2.SERVICE_INSTANCE_ID, LEFTSIDE:recordlayout1.CUSTOMER_ID, RIGHTSIDE:recordlayout2.CUSTOMER_ID, LEFTSIDE:recordlayout1.STREET_NM, LEFTSIDE:recordlayout1.STREET_DIR_CD, LEFTSIDE:recordlayout1.CIVIC_NUM, LEFTSIDE:recordlayout1.CIVIC_NUM_SFX_TXT, LEFTSIDE:recordlayout1.UNIT_NUM, LEFTSIDE:recordlayout1.MUNIC_NM, LEFTSIDE:recordlayout1.PROV_STATE_CD, LEFTSIDE:recordlayout1.POSTAL_ZIP_CD_TXT, LEFTSIDE:recordlayout1.SERVICE_INSTANCE_ACTVN_DT, LEFTSIDE:recordlayout1.SERVICE_INSTANCE_STAT_CD, LEFTSIDE:recordlayout1.SERVICE_INSTANCE_STAT_DT, RIGHTSIDE:recordlayout2.BTN, RIGHTSIDE:recordlayout2.SERVICE_RESRC_ALIAS_TYPE_CD
   /COLLATINGSEQUENCE DEFAULT ASCII

   /RECORDLAYOUT recordlayout1 { SERVICE_INSTANCE_ID CHARACTER 18, BILLING_ACCOUNT_ID CHARACTER 18, CUSTOMER_ID CHARACTER 9, STREET_NM CHARACTER 40, STREET_DIR_CD CHARACTER 2, CIVIC_NUM CHARACTER 7, CIVIC_NUM_SFX_TXT CHARACTER 5, UNIT_NUM CHARACTER 6, MUNIC_NM CHARACTER 40, PROV_STATE_CD CHARACTER 2, POSTAL_ZIP_CD_TXT CHARACTER 9, SERVICE_INSTANCE_ACTVN_DT CHARACTER 10, SERVICE_INSTANCE_STAT_CD CHARACTER 1, SERVICE_INSTANCE_STAT_DT CHARACTER 10}
   /RECORDLAYOUT recordlayout2 { SERVICE_INSTANCE_ID CHARACTER 18, WTN CHARACTER 12, BTN CHARACTER 12, CUSTOMER_ID CHARACTER 9, SERVICE_RESRC_ALIAS_TYPE_CD CHARACTER 4}

   /SILENT
   /END
EOF


