#!/usr/bin/ksh

echo "Step 6.10: Joining the files from steps 6.6 and 6.9."

syncsort << EOF
   /INFILE "$1" 65535
   /JOINKEYS Fixed_Field_LH_RL.DISCRETE_CODE
   /INFILE "$2" 65535
   /JOINKEYS Fixed_Field_RH_RL.DISCRETE_CODE

   /OUTFILE "$3" OVERWRITE
   /REFORMAT LEFTSIDE:__Field_1, RIGHTSIDE:__Field_2, RIGHTSIDE:__Field_3
   /COLLATINGSEQUENCE DEFAULT ASCII

   /RECORDLAYOUT Fixed_Field_LH_RL { DISCRETE_CODE CHARACTER 10, TN CHARACTER 10}
   /RECORDLAYOUT Fixed_Field_RH_RL { DISCRETE_CODE CHARACTER 10, CAPTION CHARACTER 10}
   /DERIVEDFIELD NON_PUB ' '
   /DERIVEDFIELD __Field_1 Fixed_Field_LH_RL.TN CHARACTER 10
   /DERIVEDFIELD __Field_2 Fixed_Field_RH_RL.CAPTION CHARACTER 10
   /DERIVEDFIELD __Field_3 NON_PUB CHARACTER 1

   /SILENT
   /END
EOF

return $?