#!/usr/bin/ksh

echo "Step 1a: Processing the Customer Profile PDS extract."

syncsort << EOF
   /INFILE "$1" 65535
   /FIELDS SERVICE_INSTANCE_ID 1 character 18
   /FIELDS CUSTOMER_ID 84 character 9
   /FIELDS SERVICE_RESRC_ALIAS_TYPE_CD 93 character 4
   /FIELDS WTN 113 character 12
   /FIELDS EFF_END_DATE 632 character 19
   /FIELDS ALIAS_STATUS_CODE 651 character 1
   /KEYS SERVICE_INSTANCE_ID

   /CONDITION filter ((SERVICE_RESRC_ALIAS_TYPE_CD = "TN  ") or (SERVICE_RESRC_ALIAS_TYPE_CD = "SRTN")) and ((ALIAS_STATUS_CODE = "A") or (ALIAS_STATUS_CODE = "S") and (EFF_END_DATE = ""))
   /INCLUDE filter

   /OUTFILE "$2" OVERWRITE
   /REFORMAT SERVICE_INSTANCE_ID, WTN, WTN, CUSTOMER_ID, SERVICE_RESRC_ALIAS_TYPE_CD, ALIAS_STATUS_CODE
   /COLLATINGSEQUENCE DEFAULT ASCII

   /SILENT
   /END
EOF

return $?
