#!/usr/bin/ksh

echo "Step 0501: Joining the files from credit service"

syncsort << EOF
   /INFILE "$1" 65535
   /JOINKEYS LeftHandFile_RecordLayout.CREDIT_PROFILE_ID
   /INFILE "$2" 65535
   /JOINKEYS RightHandFile_RecordLayout.CREDIT_PROFILE_ID

   /OUTFILE "$3" 65535 OVERWRITE
   /REFORMAT RIGHTSIDE:RightHandFile_RecordLayout.CREDIT_PROFILE_ID, LEFTSIDE:LeftHandFile_RecordLayout.IDENTIFICATION_NUM_DL, RIGHTSIDE:RightHandFile_RecordLayout.IDENTIFICATION_NUM_SIN  
   /COLLATINGSEQUENCE DEFAULT ASCII

   /RECORDLAYOUT LeftHandFile_RecordLayout  { CREDIT_PROFILE_ID CHARACTER 18, IDENTIFICATION_TYP_CD CHARACTER 3, IDENTIFICATION_NUM_DL CHARACTER 50}
   /RECORDLAYOUT RightHandFile_RecordLayout { CREDIT_PROFILE_ID CHARACTER 18, IDENTIFICATION_TYP_CD CHARACTER 3, IDENTIFICATION_NUM_SIN CHARACTER 50}
   
   /SILENT
   /END
EOF

return $?

