#!/usr/bin/ksh

echo "Step 12a: Joining the files from steps 5 and 9."

syncsort << EOF
   /INFILE "$1" 65535
   /JOINKEYS SORTED recordlayout1.CUSTOMER_ID
   /INFILE "$2" 65535
   /JOINKEYS SORTED recordlayout2.CUSTOMER_ID
   
   /OUTFILE "$3" 65535 OVERWRITE
   /REFORMAT LEFTSIDE:recordlayout1.BILLING_ACCOUNT_ID, LEFTSIDE:recordlayout1.CUSTOMER_ID, LEFTSIDE:recordlayout1.CUSTOMER_ID_PREV, RIGHTSIDE:recordlayout2.CUSTOMER_ID, LEFTSIDE:recordlayout1.FIRST_NM, LEFTSIDE:recordlayout1.MIDDLE_NM, LEFTSIDE:recordlayout1.LAST_NM, LEFTSIDE:recordlayout1.STREET_NM, LEFTSIDE:recordlayout1.STREET_DIR_CD, LEFTSIDE:recordlayout1.CIVIC_NUM, LEFTSIDE:recordlayout1.CIVIC_NUM_SFX_TXT, LEFTSIDE:recordlayout1.UNIT_NUM, LEFTSIDE:recordlayout1.MUNIC_NM, LEFTSIDE:recordlayout1.PROV_STATE_CD, LEFTSIDE:recordlayout1.POSTAL_ZIP_CD_TXT, LEFTSIDE:recordlayout1.CUST_TYPE_CD, LEFTSIDE:recordlayout1.RISK_IND_CD, LEFTSIDE:recordlayout1.FIRST_NM_BILLING, LEFTSIDE:recordlayout1.MIDDLE_NM_BILLING, LEFTSIDE:recordlayout1.LAST_NM_BILLING, RIGHTSIDE:recordlayout2.IDENTIFICATION_NUM_DL, RIGHTSIDE:recordlayout2.IDENTIFICATION_NUM_SIN
   /COLLATINGSEQUENCE DEFAULT ASCII

   /RECORDLAYOUT recordlayout1 { CUSTOMER_ID CHARACTER 9, CUSTOMER_ID_PREV CHARACTER 9, BILLING_ACCOUNT_ID CHARACTER 18, FIRST_NM CHARACTER 60, MIDDLE_NM CHARACTER 60, LAST_NM CHARACTER 60, STREET_NM CHARACTER 40, STREET_DIR_CD CHARACTER 2, CIVIC_NUM CHARACTER 7, CIVIC_NUM_SFX_TXT CHARACTER 5, UNIT_NUM CHARACTER 6, MUNIC_NM CHARACTER 40, PROV_STATE_CD CHARACTER 2, POSTAL_ZIP_CD_TXT CHARACTER 9, CUST_TYPE_CD CHARACTER 1, RISK_IND_CD CHARACTER 2, FIRST_NM_BILLING CHARACTER 60, MIDDLE_NM_BILLING CHARACTER 60, LAST_NM_BILLING CHARACTER 60}
   /RECORDLAYOUT recordlayout2 { CUSTOMER_ID CHARACTER 9, IDENTIFICATION_NUM_DL CHARACTER 50, IDENTIFICATION_NUM_SIN CHARACTER 50}

   /SILENT
   /END
EOF

return $?
