#!/usr/bin/ksh

echo "Step 2: Processing the Customer ODS extract."

syncsort << EOF
   /INFILE "$1" 65535
   /FIELDS SERVICE_INSTANCE_ID 1 character 18
   /FIELDS CUSTOMER_ID 57 character 9
   /FIELDS SERVICE_INSTANCE_ACTVN_DT 70 character 10
   /FIELDS SERVICE_INSTANCE_STAT_CD 89 character 1
   /FIELDS SERVICE_INSTANCE_STAT_DT 90 character 10
   /FIELDS BILLING_ACCOUNT_ID 340 character 18
   /FIELDS UNIT_NUM 385 character 6
   /FIELDS CIVIC_NUM 391 character 7
   /FIELDS CIVIC_NUM_SFX_TXT 398 character 5
   /FIELDS STREET_NM 403 character 40
   /FIELDS STREET_DIR_CD 443 character 2
   /FIELDS MUNIC_NM 445 character 40
   /FIELDS PROV_STATE_CD 485 character 2
   /FIELDS POSTAL_ZIP_CD_TXT 487 character 9
   /KEYS SERVICE_INSTANCE_ID
   
   /OUTFILE "$2" OVERWRITE
   /REFORMAT SERVICE_INSTANCE_ID, BILLING_ACCOUNT_ID, CUSTOMER_ID, STREET_NM, STREET_DIR_CD, CIVIC_NUM, CIVIC_NUM_SFX_TXT, UNIT_NUM, MUNIC_NM, PROV_STATE_CD, POSTAL_ZIP_CD_TXT, SERVICE_INSTANCE_ACTVN_DT, SERVICE_INSTANCE_STAT_CD, SERVICE_INSTANCE_STAT_DT
   /COLLATINGSEQUENCE DEFAULT ASCII

   /SILENT
   /END
EOF

return $?
