#!/usr/bin/ksh

echo "Step 0501: Joining the files from credit service"

syncsort << EOF
   /INFILE "$1" 65535
   /JOINKEYS LeftHandFile_RecordLayout.CREDIT_PROFILE_ID
   /INFILE "$2" 65535
   /JOINKEYS RightHandFile_RecordLayout.CREDIT_PROFILE_ID

   /OUTFILE "$3" 65535 OVERWRITE
   /REFORMAT LEFTSIDE:LeftHandFile_RecordLayout.CUSTOMER_ID, RIGHTSIDE:RightHandFile_RecordLayout.DL_IDENTIFICATION_NUM, RIGHTSIDE:RightHandFile_RecordLayout.SIN_IDENTIFICATION_NUM  
   /COLLATINGSEQUENCE DEFAULT ASCII

   /RECORDLAYOUT LeftHandFile_RecordLayout { CREDIT_PROFILE_ID CHARACTER 18, CUSTOMER_ID CHARACTER 9, CREDIT_VALUE CHARACTER 1, BIRTH_DT CHARACTER 10, EMPLOYMENT_STATUS_CD CHARACTER 2, RESIDENCY_CD CHARACTER 2, LEGAL_CARE_CD CHARACTER 2, CRED_CHECK_CONSENT_CD CHARACTER 2, PRIM_CRED_CARD_TYPE_CD CHARACTER 3, SEC_CRED_CARD_TYPE_CD CHARACTER 4}
   /RECORDLAYOUT RightHandFile_RecordLayout { CREDIT_PROFILE_ID CHARACTER 18,  DL_IDENTIFICATION_NUM CHARACTER 50, SIN_IDENTIFICATION_NUM CHARACTER 50}
   
   /SILENT
   /END
EOF

return $?

