#!/usr/bin/ksh

echo "Step 3: Processing the Billing extract."

syncsort << EOF
   /INFILE "$1" 65535
   /FIELDS BILLING_ACCOUNT_ID 1 character 18
   /FIELDS CUSTOMER_ID 188 character 9
   /FIELDS RISK_IND_CD 109 character 2
   /FIELDS FIRST_NM 583 character 60
   /FIELDS MIDDLE_NM 643 character 60
   /FIELDS LAST_NM 703 character 60
   /FIELDS UNIT_NUM 2422 character 6
   /FIELDS CIVIC_NUM 2428 character 7
   /FIELDS CIVIC_NUM_SFX_TXT 2435 character 5
   /FIELDS STREET_NM 2440 character 40
   /FIELDS STREET_DIR_CD 2490 character 2
   /FIELDS MUNIC_NM 2492 character 40
   /FIELDS PROV_STATE_CD 2532 character 2
   /FIELDS POSTAL_ZIP_CD_TXT 2534 character 9
   /KEYS CUSTOMER_ID
   
   /OUTFILE "$2" OVERWRITE
   /REFORMAT CUSTOMER_ID, BILLING_ACCOUNT_ID, STREET_NM, STREET_DIR_CD, CIVIC_NUM, CIVIC_NUM_SFX_TXT, UNIT_NUM, MUNIC_NM, PROV_STATE_CD, POSTAL_ZIP_CD_TXT, RISK_IND_CD, FIRST_NM, MIDDLE_NM, LAST_NM
   /COLLATINGSEQUENCE DEFAULT ASCII

   /SILENT
   /END
EOF

return $?
