package com.telus.credit.wlnprflmgt.webservice.service;

import java.util.Date;
import java.util.List;

import javax.annotation.Resource;
import javax.jws.WebService;
import javax.xml.ws.BindingType;
import javax.xml.ws.WebServiceContext;

import com.telus.credit.wlnprflmgt.domain.ConsumerCreditProfile;
import com.telus.credit.wlnprflmgt.domain.CreditProfileSearchResult;
import com.telus.credit.wlnprflmgt.domain.credit.common.CreditIdentification;
import com.telus.credit.wlnprflmgt.domain.credit.common.CreditProfileData;
import com.telus.credit.wlnprflmgt.domain.enterprise.common.AuditInfo;
import com.telus.framework.ws.jaxws.SpringBeanLookupHelper;
import com.telus.wsdl.cmo.ordermgmt.wlncreditprofilemanagementservice_2.PolicyException;
import com.telus.wsdl.cmo.ordermgmt.wlncreditprofilemanagementservice_2.ServiceException;
import com.telus.wsdl.cmo.ordermgmt.wlncreditprofilemanagementservice_2.WLNCreditProfileManagementServicePortType;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */

@WebService(portName = "WLNCreditProfileManagementServicePort", serviceName = "WLNCreditProfileManagementService_v2_0", targetNamespace = "http://telus.com/wsdl/CMO/OrderMgmt/WLNCreditProfileManagementService_2", wsdlLocation = "/wsdls/WLNCreditProfileManagementService_v2_0.wsdl", endpointInterface = "com.telus.wsdl.cmo.ordermgmt.wlncreditprofilemanagementservice_2.WLNCreditProfileManagementServicePortType")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class WLNCreditProfileManagementServicePortImpl
    implements WLNCreditProfileManagementServicePortType
{

    @Resource
    private WebServiceContext m_webserviceCtx;

    private WLNCreditProfileManagementServicePortType m_WLNCreditProfileManagementServicePortTypeImpl;

    public WLNCreditProfileManagementServicePortImpl() {
    }

    /**
     *
     * @param customerId
     * @param auditInfo
     * @return
     *     returns com.telus.credit.wlnprflmgt.domain.ConsumerCreditProfile
     * @throws ServiceException
     * @throws PolicyException
     */
    @Override
    public ConsumerCreditProfile getCreditProfileByCustomerId(long customerId, AuditInfo auditInfo)
        throws PolicyException, ServiceException
    {
	return getWLNCreditProfileManagementServicePortTypeImpl().getCreditProfileByCustomerId( customerId,auditInfo);
    }

    /**
     *
     * @param creditIdentification
     * @param auditInfo
     * @return
     *     returns java.util.List<com.telus.credit.wlnprflmgt.domain.CreditProfileSearchResult
     * @throws ServiceException
     * @throws PolicyException
     */
    @Override
    public List<CreditProfileSearchResult> searchCreditProfileByCreditId(CreditIdentification creditIdentification, AuditInfo auditInfo)
        throws PolicyException, ServiceException
    {
        return getWLNCreditProfileManagementServicePortTypeImpl().searchCreditProfileByCreditId( creditIdentification, auditInfo );
    }

    /**
     *
     * @param customerId
     * @param auditInfo
     * @throws ServiceException
     * @throws PolicyException
     */
    @Override
    public void expireCreditProfileByCustomerId(long customerId, AuditInfo auditInfo)
        throws PolicyException, ServiceException
    {
	getWLNCreditProfileManagementServicePortTypeImpl().expireCreditProfileByCustomerId( customerId, auditInfo );
    }

    /**
     *
     * @param creditIdentification
     * @param customerId
     * @param birthDate
     * @param auditInfo
     * @return
     *     returns java.util.List<com.telus.credit.wlnprflmgt.domain.CreditProfileSearchResult>
     * @throws ServiceException
     * @throws PolicyException
     */
    @Override
    public List<CreditProfileSearchResult> searchCreditProfileByCreditAndCustomerData(List<Long> customerId, Date birthDate, CreditIdentification creditIdentification, AuditInfo auditInfo)
        throws PolicyException, ServiceException
    {
    	return getWLNCreditProfileManagementServicePortTypeImpl().searchCreditProfileByCreditAndCustomerData(customerId, birthDate, creditIdentification, auditInfo);
    }

    /**
     *
     * @param creditProfileData
     * @param auditInfo
     * @return
     *     returns com.telus.credit.wlnprflmgt.domain.ConsumerCreditProfile
     * @throws ServiceException
     * @throws PolicyException
     */
    @Override
    public ConsumerCreditProfile createCreditProfile(CreditProfileData creditProfileData, AuditInfo auditInfo)
        throws PolicyException, ServiceException
    {
    	return getWLNCreditProfileManagementServicePortTypeImpl().createCreditProfile(creditProfileData, auditInfo);
    }

    /**
     *
     * @param customerId
     * @param auditInfo
     * @throws ServiceException
     * @throws PolicyException
     */
    @Override
    public void unmergeCreditProfile(long customerId, AuditInfo auditInfo)
        throws PolicyException, ServiceException
    {
    	getWLNCreditProfileManagementServicePortTypeImpl().unmergeCreditProfile(customerId, auditInfo);
    }
    
    
    /**
     * 
     * @param customerId
     * @param auditInfo
     * @return
     *     returns java.util.List<com.telus.credit.wlnprflmgt.domain.CreditProfileSearchResult>
     * @throws ServiceException
     * @throws PolicyException
     */
    @Override
    public List<CreditProfileSearchResult> searchLinkedCreditProfileList(long customerId, AuditInfo auditInfo)
        throws PolicyException, ServiceException
    {
    	 return getWLNCreditProfileManagementServicePortTypeImpl().searchLinkedCreditProfileList(customerId, auditInfo);
    }

    /**
     *
     * @return
     *     returns java.lang.String
     * @throws ServiceException
     * @throws PolicyException
     */
    @Override
    public String ping()
        throws PolicyException, ServiceException
    {
        return getWLNCreditProfileManagementServicePortTypeImpl().ping();
    }

    private WLNCreditProfileManagementServicePortType getWLNCreditProfileManagementServicePortTypeImpl() {
        if ( m_WLNCreditProfileManagementServicePortTypeImpl == null) {
             m_WLNCreditProfileManagementServicePortTypeImpl = (WLNCreditProfileManagementServicePortType) SpringBeanLookupHelper.getBean(m_webserviceCtx, "wlnCrdProfileMgtService");
        }
        return m_WLNCreditProfileManagementServicePortTypeImpl;
    }

}
