
package com.telus.credit.orderDepositCalculator.webservice.service;

import javax.jws.WebService;
import javax.xml.ws.BindingType;
import javax.annotation.Resource;
import javax.xml.ws.WebServiceContext;
import com.telus.framework.ws.jaxws.SpringBeanLookupHelper;

import com.telus.credit.orderDepositCalculator.webservice.OrderDepositCalculatorServiceV10PortType;
import com.telus.credit.orderDepositCalculator.webservice.PolicyException;
import com.telus.credit.orderDepositCalculator.webservice.ServiceException;
import com.telus.credit.orderDepositCalculator.domain.CalculateDeposit;
import com.telus.credit.orderDepositCalculator.domain.CalculateDepositResponse;
import com.telus.credit.orderDepositCalculator.domain.GetEquipmentQualificationList;
import com.telus.credit.orderDepositCalculator.domain.GetEquipmentQualificationListResponse;
import com.telus.tmi.xmlschema.xsd.enterprise.basetypes.types.ping_v1.Ping;
import com.telus.tmi.xmlschema.xsd.enterprise.basetypes.types.ping_v1.PingResponse;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.3-06/19/2008 07:03 PM(bt)
 * Generated source version: 2.1
 * 
 */
@WebService(portName = "OrderDepositCalculatorServicePort", serviceName = "OrderDepositCalculatorService_v1_0", targetNamespace = "http://telus.com/wsdl/CMO/OrderMgmt/OrderDepositCalculatorService_1", wsdlLocation = "/wsdls/OrderDepositCalculatorService_v1_0.wsdl", endpointInterface = "com.telus.credit.orderDepositCalculator.webservice.OrderDepositCalculatorServiceV10PortType")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class OrderDepositCalculatorServicePortImpl
    implements OrderDepositCalculatorServiceV10PortType
{
    @Resource
    private WebServiceContext m_webserviceCtx;
	
	private OrderDepositCalculatorServiceV10PortType m_OrderDepositCalculatorServicePortTypeImpl;

    public OrderDepositCalculatorServicePortImpl() {
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.credit.orderDepositCalculator.domain.CalculateDepositResponse
     * @throws ServiceException
     * @throws PolicyException
     */
    public CalculateDepositResponse calculateDeposit(CalculateDeposit parameters)
        throws PolicyException, ServiceException
    {
        return getOrderDepositCalculatorServicePortTypeImpl().calculateDeposit(parameters);
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.credit.orderDepositCalculator.domain.GetEquipmentQualificationListResponse
     * @throws ServiceException
     * @throws PolicyException
     */
    public GetEquipmentQualificationListResponse getEquipmentQualificationList(GetEquipmentQualificationList parameters)
        throws PolicyException, ServiceException
    {
        return getOrderDepositCalculatorServicePortTypeImpl().getEquipmentQualificationList(parameters);
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.tmi.xmlschema.xsd.enterprise.basetypes.types.ping_v1.PingResponse
     * @throws ServiceException
     * @throws PolicyException
     */
    public PingResponse ping(Ping parameters)
        throws PolicyException, ServiceException
    {
        return getOrderDepositCalculatorServicePortTypeImpl().ping(parameters);
    }
	
	private OrderDepositCalculatorServiceV10PortType getOrderDepositCalculatorServicePortTypeImpl() {
        if ( m_OrderDepositCalculatorServicePortTypeImpl == null) {
             m_OrderDepositCalculatorServicePortTypeImpl = (OrderDepositCalculatorServiceV10PortType) SpringBeanLookupHelper.getBean(m_webserviceCtx, "orderDepositCalculatorService");
        }
        return m_OrderDepositCalculatorServicePortTypeImpl;
    }

}
