package com.telus.credit.crda.util;



public class EnterpriseCreditAssessmentConsts {

    public final static String REF_PDS_T_CAR_TYP = "CAR_TYP";
    public final static String REF_PDS_T_CAR_SUB_TYP = "CAR_SUBTYP";
    public final static String REF_PDS_T_CREDIT_LOB = "CREDIT_LOB";
    public final static String REF_PDS_T_CAR_STATUS = "CAR_STATUS";
    public final static String REF_PDS_T_CAR_ACT_RSN = "CAR_ACT_RSN";
    public final static String REF_PDS_T_CREDIT_FRAUD_IND = "CREDIT_FRAUD_IND";
    public final static String REF_PDS_T_CREDIT_VALUE_CODE = "CREDIT_VALUE_CODE";
    public final static String REF_PDS_T_YES_NO_NA = "YES_NO_NA";


    //is calling decision-sys required ?
    public final static String DECISIONING_IS_REQUIRED = "DECISION";
    public final static String DECISIONING_IS_NOT_REQUIRED = "NONDECISION";

    //asmt types
    public final static String ASMT_TYPE_OVRD_ASMT = "OVRD_ASSESSMENT";
    public final static String ASMT_TYPE_FULL_ASMT = "FULL_ASSESSMENT";
    public final static String ASMT_TYPE_AUDIT = "AUDIT";


    //Full asmt sub types
    public final static String ASMT_SUB_TYPE_AUTO_ASMT = "AUTO_ASSESSMENT";
    public final static String ASMT_SUB_TYPE_GET_BUREAU_DATA = "GET_BUREAU_DATA";
    public final static String ASMT_SUB_TYPE_MONTHLY_CVUD = "MONTHLY_CVUD";
    public final static String ASMT_SUB_TYPE_NEW_ACC_ASSESSMENT = "NEW_ACC_ASSESSMENT";
    public final static String ASMT_SUB_TYPE_REOPEN_ASSESSMENT = "REOPEN_ASSESSMENT";
    public final static String ASMT_SUB_TYPE_MANUAL_ASSESSMENT = "MANUAL_ASSESSMENT";


    //Override asmt sub types
    public final static String ASMT_SUB_TYPE_MANUAL_OVRD = "MANUAL_OVERRIDE";
    public final static String ASMT_SUB_TYPE_UNMERGED = "UNMERGED";
    public final static String ASMT_SUB_TYPE_CANCEL_DEPOSIT_INV = "CANCEL_DEPOSIT_INV";
    public final static String ASMT_SUB_TYPE_DEPOSIT_DOWNGRADE = "DEPOSIT_DOWNGRADE";
    @Deprecated
    public final static String ASMT_SUB_TYPE_UPGRADE = "AUTO_UPGRADE";//remains here only to support old assessments

    //Auditasmt sub types
    public final static String ASMT_SUB_TYPE_CONSENT = "BUREAU_CONSENT";


    //	general
    public final static String EMPTY_STR = "";
    public final static String WLN_LINE_OF_BUSINESS = "WIRELINE";
    public final static String WLS_LINE_OF_BUSINESS = "WIRELESS";

    //	CAR status
    public final static String CAR_STATUS_COMPLETED = "COMPLETED";
    public final static String CAR_STATUS_CANCELLED = "CANCELLED";
    public final static String CAR_STATUS_PENDING = "PENDING";


    // CAR Result Status
    public final static String CAR_RESULT_STATUS_APPROVED = "APPROVED";
    public final static String CAR_RESULT_STATUS_DENIED = "DENIED";
    public final static String CAR_RESULT_STATUS_LEGAL_NAME_VERIFIED = "LEG_NM_VERIFIED";
    public final static String CAR_RESULT_STATUS_LEGAL_NAME_NOT_VERIFIED = "LEG_NM_NOT_VER";
    public final static String CAR_RESULT_STATUS_CANCELLED = "CANCELLED";

    // CAR Activity
    public final static String CAR_ACTIVITY_VOID = "VOID";


    //FICO 
    public final static String DECISION_SYS_NAME = "FICO";
    //Fico RESULT CODES
    public final static String DECISIONING_RESULT_CD_ERROR = "ERROR";
    public final static String DECISIONING_RESULT_CD_SUCCESS = "SUCCESS";//RuleServicesConstants.ASSESSMENT_RESULT_CODE_SUCCESS
    //TODO is this Fico RESULT CODE correct?
    public final static String ASSESSMENT_REASON_CODE_FAILD_MSG_CD = "FAILD_MSG_CD_1";   
   
    //Fico REASON CODES
    public final static String DECISIONING_REASON_CD_SUCCESS = "";
    public final static String DECISIONING_REASON_CD_NOCHANGE = "NO_CHANGE";
    public final static String DECISIONING_REASON_CD_BUREAU_REQUIRED = "BUREAU_REQUIRED";
    
    // RESILIENCE codes
    public final static String ASSESSMENT_RESILIENCE = "RESILIENCE"; 
    public final static String DECISIONING_RESILIENCE_ASMT_MSG_CD = "ASMT_BYPASSED";
  
   
 
    //BUREAU Transaction Status
    public final static String CREDIT_BUREAU_TRN_STATUS_ACTIVE = "1";
    public final static String CREDIT_BUREAU_TRN_STATUS_VOID = "2";


    //
    public final static String BUREAU_REPORT_STATUS_COMPLETED = CAR_STATUS_COMPLETED;
    public final static String BUREAU_REPORT_STATUS_VOID = "VOID";

    //TODO get from REFPDS message table "Credit Management Messages" by looking up the msg using keys :CRDA-TEXT-001...006
    /*    
	CRDA_COMMENT_TEXT_002 ->CRDA-TEXT-002
		FULL_ASSESSMENT	AUTO_ASSESSMENT	
		FULL_ASSESSMENT	REOPEN_ASSESSMENT
		FULL_ASSESSMENT	NEW_ACC_ASSESSMENT
	CRDA_COMMENT_TEXT_003 ->CRDA-TEXT-003
		OVRD_ASSESSMENT	UNMERGED
	CRDA_COMMENT_TEXT_004 ->CRDA-TEXT-004	
		FULL_ASSESSMENT	MONTHLY_CVUD	"system generated by batch or eCrda
	CRDA_COMMENT_TEXT_005 ->CRDA-TEXT-005
		OVRD_ASSESSMENT	CANCEL_DEPOSIT_INV
	CRDA_COMMENT_TEXT_006 ->CRDA-TEXT-006
		OVRD_ASSESSMENT	DEPOSIT_DOWNGRADE	
     */
    public final static String CRDA_COMMENT_TEXT_001 = "Default - Credit Assessment Not Complete";
    public final static String CRDA_COMMENT_TEXT_002 = "Automated Credit Assessment Completed";
    public final static String CRDA_COMMENT_TEXT_003 = "Unmerged Credit Profile.";
    public final static String CRDA_COMMENT_TEXT_004 = "Automated Credit Value Uprgade : ";   //Automated Credit Value Upgrade/Downgrade: X to Y "
    public final static String CRDA_COMMENT_TEXT_005 = "Cancelled Pending Deposit Order.";   
    public final static String CRDA_COMMENT_TEXT_006 = "Final Deposit Overriden/Downgraded.";  
/*    public final static String CRDA_COMMENT_TEXT_007 = "Automated Credit Assessment Completed on Re-Open Ban.";  
    public final static String CRDA_COMMENT_TEXT_008 = "Automated Credit Assessment Completed on add new Ban."; */ 
    public final static String CRDA_COMMENT_TEXT_007 = CRDA_COMMENT_TEXT_002; 
    public final static String CRDA_COMMENT_TEXT_008 = CRDA_COMMENT_TEXT_002; 
	public final static String CRDA_COMMENT_UNIFIED_CREDIT_INDICATOR = "Unified Credit Indicator: ";
	public final static String CRDA_COMMENT_UNIFIED_CREDIT_REASON = "Unified Credit Reason: ";
 
    //Credit GW
    public final static String SIMULATOR_REPROT_SOURCE_CD = "SIMULATOR";
    
	public static final String LASTCHGDATE = "[26/03/2014]";

	//Unified Credit Save Documentum Constants
    public static final String DOC_REPORT_TYPE = "REPORT_TYPE";
    public static final String DOC_CONS_CRD_RPT = "CONS_CRD_RPT_UC";
    public static final String DOC_TEXT_SPACE = "_";
    public static final String DOC_PRINTIMAGE_REPORT_EXT = ".txt";
    public static final String DOC_UC_CONTENT_TYPE = "TXT";
    public static final String DOC_IMAGE_EXTERNAL_RPT_LOC_STR = "IMAGE_EXTERNAL_RPT_LOC_STR";
    public static final String DOC_PRINTIMAGE_REPORT = "PRINTIMAGE_REPORT"; 
}
