package com.telus.credit.wlnprfldmgt.webservice.service;

import javax.annotation.Resource;
import javax.jws.WebService;
import javax.xml.ws.BindingType;
import javax.xml.ws.WebServiceContext;

import org.springframework.context.support.ClassPathXmlApplicationContext;

import com.telus.credit.wlnprfldmgt.domain.CreditProfileData;
import com.telus.credit.wlnprfldmgt.domain.CreditWorthiness;
import com.telus.credit.wlnprfldmgt.domain.RemoveWLNCreditIdentificationInfo;
import com.telus.credit.wlnprfldmgt.webservice.impl.WLNCreditProfileDataManagementServiceImpl;
import com.telus.framework.ws.jaxws.SpringBeanLookupHelper;
import com.telus.tmi.xmlschema.xsd.customer.customer.enterprisecreditassessmenttypes_v2.CreditAssessmentTransaction;
import com.telus.tmi.xmlschema.xsd.enterprise.basetypes.enterprisecommontypes_v6.AuditInfo;
import com.telus.wsdl.cmo.ordermgmt.wlncreditprofiledatamanagementservice_1.PolicyException;
import com.telus.wsdl.cmo.ordermgmt.wlncreditprofiledatamanagementservice_1.ServiceException;
import com.telus.wsdl.cmo.ordermgmt.wlncreditprofiledatamanagementservice_1.WLNCreditProfileDataManagementServicePortType;
/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.4
 * Generated source version: 2.1
 *
 */

@WebService(portName = "WLNCreditProfileDataManagementServicePort", serviceName = "WLNCreditProfileDataManagementService_v1_3", targetNamespace = "http://telus.com/wsdl/CMO/OrderMgmt/WLNCreditProfileDataManagementService_1", wsdlLocation = "/wsdls/WLNCreditProfileDataManagementService_v1_3.wsdl", endpointInterface = "com.telus.wsdl.cmo.ordermgmt.wlncreditprofiledatamanagementservice_1.WLNCreditProfileDataManagementServicePortType")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class WLNCreditProfileDataManagementServicePortImpl
    implements WLNCreditProfileDataManagementServicePortType
{

    @Resource
    private WebServiceContext m_webserviceCtx;

    //private WLNCreditProfileDataManagementServiceImpl svcImpl;
    private WLNCreditProfileDataManagementServicePortType svcImpl;

    public WLNCreditProfileDataManagementServicePortImpl() {
    }


    /**
     *
     * @param creditProfile
     * @param auditInfo
     * @throws ServiceException
     * @throws PolicyException
     */
    @Override
    public void updateCreditProfile(CreditProfileData creditProfile,
    		RemoveWLNCreditIdentificationInfo removeWLNCreditIdentificationInfo,
            String creditValueCd, String fraudIndicatorCd, AuditInfo auditInfo)
        throws PolicyException, ServiceException
    {
    	initialize();
    	svcImpl.updateCreditProfile(creditProfile, removeWLNCreditIdentificationInfo, creditValueCd, fraudIndicatorCd, auditInfo);
    }

    /**
     * Update Credit Worthiness
     *
     * @param customerId
     * @param creditWorthiness
     * @param auditInfo
     */
    @Override
    public void updateCreditWorthiness(
    		CreditAssessmentTransaction creditAssessmentTransactionResult,
            AuditInfo auditInfo)
            throws PolicyException, ServiceException
    {
        initialize();
        svcImpl.updateCreditWorthiness(creditAssessmentTransactionResult, auditInfo);
    }

    private void initialize() {
		if (svcImpl ==null) {
		    //svcImpl = (WLNCreditProfileDataManagementServiceImpl) SpringBeanLookupHelper.getBean(m_webserviceCtx,"CreditProfileMgtSvcTxProxy");
			svcImpl = (WLNCreditProfileDataManagementServicePortType) SpringBeanLookupHelper.getBean(m_webserviceCtx,"CreditProfileMgtSvcTxProxy");
		}
    }

    /**
     *
     * @return
     *     returns java.lang.String
     * @throws ServiceException
     * @throws PolicyException
     */
    public String ping()
        throws PolicyException, ServiceException
    {
    	return "Success";
    }

}
