package com.telus.credit.entprflmgt.webservice.service;

import javax.annotation.Resource;
import javax.jws.WebService;
import javax.xml.ws.BindingType;
import javax.xml.ws.WebServiceContext;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.dozer.DozerBeanMapper;

import com.telus.framework.ws.jaxws.SpringBeanLookupHelper;

import com.telus.credit.entprflmgt.domain_v1_1.ConsumerCreditProfileInfo;
import com.telus.tmi.xmlschema.xsd.enterprise.basetypes.enterprisecommontypes_v6.AuditInfo;
import com.telus.wsdl.cmo.ordermgmt.enterprisecreditprofilemanagementsvc_2.EnterpriseCreditProfileManagementServicePortType;
import com.telus.wsdl.cmo.ordermgmt.enterprisecreditprofilemanagementservice_1.EnterpriseCreditProfileManagementServiceV11PortType;
import com.telus.wsdl.cmo.ordermgmt.enterprisecreditprofilemanagementservice_1.PolicyException;
import com.telus.wsdl.cmo.ordermgmt.enterprisecreditprofilemanagementservice_1.ServiceException;

/**
 * This class was generated by the JAX-WS RI. Oracle JAX-WS 2.1.4 Generated
 * source version: 2.1
 * 
 */
@WebService(portName = "EnterpriseCreditProfileManagementServicePort", serviceName = "EnterpriseCreditProfileManagementService_v1_1", targetNamespace = "http://telus.com/wsdl/CMO/OrderMgmt/EnterpriseCreditProfileManagementService_1", wsdlLocation = "wsdls/EnterpriseCreditProfileManagementService_v1_1.wsdl", endpointInterface = "com.telus.wsdl.cmo.ordermgmt.enterprisecreditprofilemanagementservice_1.EnterpriseCreditProfileManagementServiceV11PortType")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class EnterpriseCreditProfileManagementServicePortImpl implements EnterpriseCreditProfileManagementServiceV11PortType
{
	/*
     * Log object
     */
    private static final Log log = LogFactory.getLog(EnterpriseCreditProfileManagementServicePortImpl.class);
    
    @Resource
    private WebServiceContext m_webserviceCtx;

    // injected
    private EnterpriseCreditProfileManagementServicePortType m_impl;
    private DozerBeanMapper m_mapper;
    private boolean m_initialized=false;

    
    public void init()
    {
    	if ( !m_initialized ) {
    		try {
    			m_impl = (EnterpriseCreditProfileManagementServicePortType )SpringBeanLookupHelper.getBean(m_webserviceCtx, "entCrdProfileMgtService");
    			m_mapper = (DozerBeanMapper )SpringBeanLookupHelper.getBean(m_webserviceCtx, "mapper");
    			m_initialized=true;
    			log.debug("init has completed.");
    		}
    		catch (Throwable e) {
    			log.error("Exception while calling init()" + e, e );
    			throw new RuntimeException( e );
    		}
    	}
    }

    @Override
    public void updateCreditProfile(ConsumerCreditProfileInfo consumerCreditProfileInfo_v1_1, AuditInfo auditInfo)
            throws PolicyException, ServiceException
    {
    	init();
    	com.telus.credit.entprflmgt.domain.ConsumerCreditProfileInfo consumerCreditProfileInfo_v2 = m_mapper.map(consumerCreditProfileInfo_v1_1, com.telus.credit.entprflmgt.domain.ConsumerCreditProfileInfo.class);
        try {
			m_impl.updateCreditProfile(consumerCreditProfileInfo_v2, auditInfo, null, null, null, null, null, null);
		} catch (com.telus.wsdl.cmo.ordermgmt.enterprisecreditprofilemanagementsvc_2.ServiceException e) {
			if(log != null) {
				log.error(e);
			}
			com.telus.tmi.xmlschema.xsd.common.exceptions.exceptions_v1_0.ServiceException se = new com.telus.tmi.xmlschema.xsd.common.exceptions.exceptions_v1_0.ServiceException();
			se.setErrorMessage(e.getMessage());
			com.telus.wsdl.cmo.ordermgmt.enterprisecreditprofilemanagementservice_1.ServiceException newSE = new com.telus.wsdl.cmo.ordermgmt.enterprisecreditprofilemanagementservice_1.ServiceException(e.getMessage(), se, e.getCause());
		}
        //(consumerCreditProfileInfo_v1_3, null, auditInfo);
    }


    @Override
    public String ping()
            throws PolicyException, ServiceException
    {
        return "EnterpriseCreditProfileManagementService_v1_1";
    }
}
