
package com.telus.credit.wlnprflmatch.webservice.service;

import javax.annotation.Resource;
import javax.jws.WebService;
import javax.xml.ws.BindingType;
import javax.xml.ws.WebServiceContext;

import com.telus.credit.wlnprflmatch.domain.CheckCreditProfileResponse;
import com.telus.credit.wlnprflmatch.domain.CreditIdentification;
import com.telus.framework.ws.jaxws.SpringBeanLookupHelper;
import com.telus.tmi.xmlschema.xsd.enterprise.basetypes.enterprisecommontypes_v9.AuditInfo;
import com.telus.wsdl.cmo.ordermgmt.wlncreditprofilematchsvc_1.ServiceException;
import com.telus.wsdl.cmo.ordermgmt.wlncreditprofilematchsvc_1.WLNCreditProfileMatchSvcV10PortType;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebService(portName = "WLNCreditProfileMatchSvcPort", 
serviceName = "WLNCreditProfileMatchSvc_v1_0", 
targetNamespace = "http://telus.com/wsdl/CMO/OrderMgmt/WLNCreditProfileMatchSvc_1", 
wsdlLocation = "/wsdls/WLNCreditProfileMatchSvc_v1_0.wsdl", 
endpointInterface = "com.telus.wsdl.cmo.ordermgmt.wlncreditprofilematchsvc_1.WLNCreditProfileMatchSvcV10PortType")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class WLNCreditProfileMatchSvcPortImpl  implements WLNCreditProfileMatchSvcV10PortType
{
	
	 @Resource
	 private WebServiceContext m_webserviceCtx;
     private WLNCreditProfileMatchSvcV10PortType wlnCreditProfileMatchServiceImpl;

    public WLNCreditProfileMatchSvcPortImpl() {
    }

    /**
     * 
     * @param creditIdentification
     * @param auditInfo
     * @return
     *     returns com.telus.credit.wlnprflmatch.domain.CheckCreditProfileResponse
     * @throws ServiceException
     */
    public CheckCreditProfileResponse checkCreditProfileByCreditId(CreditIdentification creditIdentification, AuditInfo auditInfo)
        throws ServiceException
    {
    	return getWLNCreditProfileMatchServicePortTypeImpl().checkCreditProfileByCreditId(creditIdentification, auditInfo);
    }

    /**
     * 
     * @return
     *     returns java.lang.String
     * @throws ServiceException
     */
    public String ping() throws ServiceException
    {
        
        return getWLNCreditProfileMatchServicePortTypeImpl().ping();
    }
    
    
   
  
   private WLNCreditProfileMatchSvcV10PortType getWLNCreditProfileMatchServicePortTypeImpl() {
       if ( wlnCreditProfileMatchServiceImpl == null) {
    	   wlnCreditProfileMatchServiceImpl = (WLNCreditProfileMatchSvcV10PortType) SpringBeanLookupHelper.getBean(m_webserviceCtx, "wlnCrdProfileMatchService");
       }
       return wlnCreditProfileMatchServiceImpl;
   }

}
