#!/usr/bin/ksh

# Title: join_input_to_customer_data.sh
# desc: This script takes two CSV files and joins them by RCID present in both files 
#       to produce third file with all the records matched.
#

# Validate the number of input parameters
if [ $# -eq 3 ]; then
    WIRELINE_CUSTOMERS_FILE=$1
    WIRELESS_CUSTOMERS_FILE=$2
    OUTPUT_FILE=$3
else
    echo ""
    echo "Error Input File: $INPUT_FILE"
    echo ""
    exit 1
fi

# Actual SyncSort implementation of the script.
syncsort <<-EOF
${sortstatistic}
${sortworkspace}

/INFILE $WIRELINE_CUSTOMERS_FILE 90
/FIELDS WLN_CUSTOMER_ID 1 character 9
/FIELDS WLN_BAN_ID 10 character 10
/FIELDS WLN_DL 20 character 52
/FIELDS WLN_DOB 72 character 10
/FIELDS WLN_SIN 82 character 9
/JOINKEYS WLN_CUSTOMER_ID, WLN_BAN_ID

/INFILE $WIRELESS_CUSTOMERS_FILE 90
/FIELDS WLS_CUSTOMER_ID 1 character 9
/FIELDS WLS_BAN_ID 10 character 10
/FIELDS WLS_DL 20 character 52
/FIELDS WLS_DOB 72 character 10
/FIELDS WLS_SIN 82 character 9
/JOINKEYS WLS_CUSTOMER_ID, WLS_BAN_ID

/PADBYTE X"20"

/OUTFILE $OUTPUT_FILE OVERWRITE
/REFORMAT LEFTSIDE:WLN_CUSTOMER_ID, WLN_BAN_ID, WLN_DL, WLN_DOB, WLN_SIN, RIGHTSIDE:WLS_DL, WLS_DOB, WLS_SIN, WLS_BAN_ID
/SILENT
/WARNINGS 100
/END

EOF

syncsort <<-EOF
${sortstatistic}
${sortworkspace}

/INFILE $OUTPUT_FILE 171
/FIELDS CUSTOMER_ID 1 character 9
/FIELDS BAN_ID 162 character 10
/FIELDS WLN_DL 20 character 52
/FIELDS WLN_DOB 72 character 10
/FIELDS WLN_SIN 82 character 9
/FIELDS WLS_DL 91 character 52
/FIELDS WLS_DOB 143 character 10
/FIELDS WLS_SIN 153 character 9

/CONDITION IS_SYNC_DL WLN_DL EQ WLS_DL
/DERIVEDFIELD DERIVED_DL IF IS_SYNC_DL THEN "IN SYNC" ELSE "NOT IN SYNC"

/CONDITION IS_SYNC_SIN WLN_SIN EQ WLS_SIN
/DERIVEDFIELD DERIVED_SIN IF IS_SYNC_SIN THEN "IN SYNC" ELSE "NOT IN SYNC"

/CONDITION IS_SYNC_DOB WLN_DOB EQ WLS_DOB
/DERIVEDFIELD DERIVED_DOB IF IS_SYNC_DOB THEN "IN SYNC" ELSE "NOT IN SYNC"

/DERIVEDFIELD delim "|"

/PADBYTE X"20"

/OUTFILE $OUTPUT_FILE OVERWRITE
/REFORMAT CUSTOMER_ID, delim, BAN_ID, delim, DERIVED_DL, delim, DERIVED_DOB, delim, DERIVED_SIN
/TITLE "CUSTOMER_ID|BAN|DRIVERS_LICENSE|DATE_OF_BIRTH|SIN"

/SILENT
/WARNINGS 100
/END

EOF

syncsort <<-EOF
${sortstatistic}
${sortworkspace}

/INFILE $OUTPUT_FILE "|"
/FIELDS CUSTOMER_ID 1: - 1:
/FIELDS BAN 2: - 2:
/FIELDS DRIVERS_LICENSE 3: - 3:
/FIELDS DATE_OF_BIRTH 4: - 4:
/FIELDS SIN 5: - 5:

/CONDITION IS_NOT_SYNC DRIVERS_LICENSE EQ "NOT IN SYNC" OR DATE_OF_BIRTH EQ "NOT IN SYNC" OR SIN EQ "NOT IN SYNC"
/INCLUDE IS_NOT_SYNC

/DERIVEDFIELD delim "|"

/PADBYTE X"20"

/OUTFILE $OUTPUT_FILE OVERWRITE
/REFORMAT CUSTOMER_ID, delim, BAN, delim, DRIVERS_LICENSE, delim, DATE_OF_BIRTH, delim, SIN
/TITLE "CUSTOMER_ID|BAN|DRIVERS_LICENSE|DATE_OF_BIRTH|SIN"

/SILENT
/WARNINGS 100
/END

EOF

return $?